name: check_version
description: Check Android/iOs store version and provide update alert if update is available on stores.
version: 0.0.5
homepage: https://github.com/wesleytoshio/check_version

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  html: ^0.14.0+4
  url_launcher: ^5.4.2
  package_info: ^0.4.3+2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
